FROM gitea/gitea:latest

USER root

# Git identity (Method 1 like your past setup)
RUN git config --global user.name "Cheang Yuheng, Kane" && \
    git config --global user.email "2302033@sit.singaporetech.edu.sg"

USER git
