name: Selenium UI Tests

on: [push, pull_request]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js dependencies
        run: npm install

      - name: Start web app
        run: |
          nohup npm start > app.log 2>&1 &
          for i in {1..20}; do
            curl -sf http://localhost:3000 && break
            echo "Waiting for webapp..."
            sleep 3
          done

      - name: Install Selenium dependencies
        run: npm install selenium-webdriver chromedriver

      - name: Run Selenium Tests & Save Report
        run: |
          mkdir -p selenium-report
          node app/tests/SeleniumTest.mjs local | tee selenium-report/test-results.txt
        continue-on-error: true

      - name: Upload Selenium test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-report
          path: selenium-report/test-results.txt
