name: UI + Unit Testing with Selenium

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    container:
      image: node:20
      options: --network-alias=testcontainer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: app
        run: npm install

      - name: Start web app
        working-directory: app
        run: |
          nohup node index.js &
          sleep 5

      - name: Wait for web app
        run: |
          for i in {1..10}; do
            curl -s http://testcontainer || sleep 2
          done

      - name: Wait for Selenium
        run: |
          for i in {1..10}; do
            curl -s http://selenium:4444/wd/hub/status | grep '"ready":true' && break || sleep 2
          done

      - name: Run Selenium test
        working-directory: app
        run: |
          npm install --no-save selenium-webdriver
          node SeleniumTest.mjs github
